# Generated by Django 5.2.13 on 2026-08-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('grade', models.CharField(choices=[('I', 'Grade I'), ('II', 'Grade II'), ('III', 'Grade III'), ('IV', 'Grade IV'), ('SPECIAL', 'Special')], max_length=10)),
                ('employee_count', models.PositiveIntegerField()),
            ],
        ),
    ]
