# Generated by Django 5.2.13 on 2026-08-19 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_alter_branch_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('tag_number', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(choices=[('PC', 'PC'), ('MONITOR', 'Monitor'), ('SCANNER', 'Scanner'), ('PRINTER', 'Printer'), ('OTHER', 'Other')], max_length=20)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('DIAGNOSED_FUNCTIONAL', 'Diagnosed — Functional'), ('DIAGNOSED_NOT_FUNCTIONAL', 'Diagnosed — Not Functional'), ('REPAIRED', 'Repaired'), ('RETURNED_TO_BRANCH', 'Returned to Branch'), ('FOR_DISPOSAL', 'For Disposal'), ('DISPOSED', 'Disposed')], default='RECEIVED', max_length=30)),
                ('condition_notes', models.TextField(blank=True)),
                ('date_received', models.DateField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='branches.branch')),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logged_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='inventory.device')),
            ],
            options={
                'verbose_name_plural': 'Status history',
                'ordering': ['-timestamp'],
            },
        ),
    ]
