# Generated by Django 5.2.13 on 2026-08-24 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('RAM', 'RAM'), ('HDD', 'Hard Disk'), ('SSD', 'SSD'), ('PRINTER_PART', 'Printer Component'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('INSTALLED', 'Installed'), ('DISPOSED', 'Disposed')], default='IN_STOCK', max_length=20)),
                ('date_logged', models.DateField(auto_now_add=True)),
                ('source_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salvaged_components', to='inventory.device')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('installation_note', models.TextField(blank=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='inventory.component')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components_used', to='inventory.device')),
                ('installed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components_installed', to=settings.AUTH_USER_MODEL)),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='components_removed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Component usages',
                'ordering': ['-installed_at'],
            },
        ),
    ]
