# Generated by Django 5.2.4 on 2026-08-25 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_component_componentusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentusage',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='inventory.component'),
        ),
    ]
