# Generated by Django 5.2.4 on 2026-09-22 22:56

from django.db import migrations


def backfill_branch(apps, schema_editor):
    StatusHistory = apps.get_model("inventory", "StatusHistory")
    for history in StatusHistory.objects.select_related("device").all():
        history.branch = history.device.branch
        history.save(update_fields=["branch"])

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_statushistory_branch_disposalrecommendation'),
    ]

    operations = [
        migrations.RunPython(backfill_branch, migrations.RunPython.noop),
    ]
