# Generated by Django 5.2.4 on 2026-09-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportline',
            name='discrepancy',
            field=models.IntegerField(verbose_name='In Progress'),
        ),
    ]
